[colors]
background = '#232a2e'
foreground = '#d3c6aa'

cursor_bg = '#a7c080'
cursor_fg = '#232a2e'
cursor_border = '#a7c080'

selection_bg = '#859e6b'
selection_fg = '#d3c6aa'

ansi = ['#2d353b', '#dc7763', '#67c060', '#f0dd6b', '#99b66d', '#435822', '#a7c080', '#c4c9bd']
brights = ['#888b82', '#ffaf9f', '#9ce695', '#fff2a5', '#bbd397', '#e2f9bf', '#f0ffd8', '#fcfff8']
